<?php

namespace SuiviBundle\Repository;

/**
 * RegimeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimeRateRepository extends \Doctrine\ORM\EntityRepository
{
}
