<?php

namespace SuiviBundle\Repository;

/**
 * RegimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimeRepository extends \Doctrine\ORM\EntityRepository
{
}
