<?php

namespace GUBundle\Repository;

/**
 * SignalerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalerRepository extends \Doctrine\ORM\EntityRepository
{
}
